### ISSUE TITLE
Strange ordering effect in sections

### ISSUE THREAD

**Issue by mdda** [Sdju/js-ini#1]
Thanks for the package (which works more predictably than others).  But there's still a wrinkle for me, where the keys within a section are being reverse-ordered, but not the outside-section keys (it seems like your tests coincidentally side-step this) : 

As expected:
```
var a={ '1': 'All', '2': 'in', '3': 'order.' };
ini.encode(a);
// '1=All\n2=in\n3=order.'
```
Not as expected:
```
var a={'section':{ '1': 'All', '2': 'in', '3': 'order.' }};
ini.encode(a);
// '\n[section]\n3=order.\n2=in\n1=All'
```

**Comment by Sdju** [comment]
Thanks for your issue about the key order in encode. Ive completely rewritten the order of string creating, it is more optimized and matching up with your expectations now. Try to update to latest version (1.1.3)

**Comment by mdda** [comment]
Awesome!  That's much better looking for the generated file (even though the loader wouldn't care : it's nice to have something more human-readable).

Thanks
