### ISSUE TITLE
Duplicated keys not working

### ISSUE THREAD

**Issue by axi92** [Sdju/js-ini#17]
Duplicated keys are not working.

configs.ini
```
[Database settings]
key=value1
key=value2
```

index.js
```
const ini = require('js-ini');
const fs = require('fs').promises;
fs.readFile('configs.ini', 'utf-8').then((txt) => {
  console.log(JSON.stringify(ini.parse(txt)));
});
```

Output:
```
{"Database settings":{"key":"value2"}}
```

**Comment by Sdju** [comment]
Hello. How do you want to solve this situation with duplicated keys? I wanted to add some options to decide merge strategies

**Comment by axi92** [comment]
I have not thought about it, is it possible to keep duplicated keys? Some inis have them.
Like build them in an array on the json object? 
In my ini the order is also important. I am sorry I know thats a lot of features.

**Comment by axi92** [comment]
Hey @Sdju I had some time but I am not that experienced with ts so I have don the parse thing in cjs.
I have just done this in about 20min or so. Just an idea how to handle multiple keys with the same name. Put them into an array.
It is this section in your ts https://github.com/Sdju/js-ini/blob/master/src/parse.ts#L76
```
            if (currentSection !== '') {
                if (result[currentSection][name] === undefined) {
                    result[currentSection][name] = val;
                }
                else {
                    console.log('handle multiple stuff');
                    let nameArray = []
                    if(typeof result[currentSection][name] === 'object'){
                      result[currentSection][name].forEach(element => {
                        nameArray.push(element)
                      });
                    } else {
                      nameArray.push(result[currentSection][name]);
                    }
                    nameArray.push(val)
                    result[currentSection][name] = nameArray;
                }
            }
```
Input ini:
```ini
[Settings]
configkey=value1
key=value2
key=value3
```
Output is like this:
```js
{
  Settings: [Object: null prototype] {
    configkey: 'value1',
    key: [ 'value2', 'value3' ]
  }
}
```

**Comment by Sdju** [comment]
Hello. Thank you. I will add it with a special option
