### ISSUE TITLE
Section keys without value will cause infinite loop

### ISSUE THREAD

**Issue by moruzerinho6** [Sdju/js-ini#19]
Given the following iniString:

```INI
[exports]
NEW!=NOVO!
Press Start For Options=Aperte &START; de novo para opções
Start To Join=Aperte &START; para entrar
Entering Options=Entrando no menu de opções...
HelpText=&BACK; Sair  &START; Selecionar / Entrar &MENULEFT;&MENURIGHT; Mover :: &MENUUP;&MENUUP;/&MENUDOWN;&MENUDOWN; Mudar dificuldade   &SELECT; (hold) Atalhos
AlternateHelpText=&SELECT;+&MENULEFT;&MENURIGHT; Mudar dificuldade &SELECT;+&START; Mudar ordenação
HeaderSubText=
SortLabel=Filtro
SpeedLabel=Velocidade
LengthLabel=Duração
StageLabel=Estágio
LongSong=Música Longa
MarathonSong=Maratona
ChartStats=Chart Info
NoAuthor=N/A
HighScore=Pontuação Alta
ChangeDifficulty=&MENULEFT;&MENURIGHT; Mudar dificuldade
ChangeSort=&START; Mudar ordenação
```

The package will start a infinite loop at js-ini/lib/stringify.js inside the stringify function `for of` loop when trying to parse `HeaderSubText=`

This happens because the loop is only expecting values of type `boolean`, `string`, `number` and `object`. However, when no value is given, it is undefined, which is its own type, `undefined`. Since no condition inside the loop is expecting undefined, the loop will run forever with `HeaderSubText` as the key but the value will never be handled. ([It's important to remember that while undefined is falsy, it is not a boolean](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#typeof_operator_and_undefined))

Proposed fix is to simply add a empty string as the value to the key (eg. `key=`) when undefined is found as the type of the value.

I'm not sure why the loop runs again with the same key, maybe a switch the casual index based for loop would help?

**Comment by Sdju** [comment]
Hello I've checked your test case. 
I didn't get inifinity loop but output was incorrect and I added new param

https://github.com/Sdju/js-ini/commit/a0c83a45f4c568feb10a909c004f8e5c329c575e
