### ISSUE TITLE
Make test for parsing not ini-like string, note in README?

### ISSUE THREAD

**Issue by vintprox** [Sdju/js-ini#2]
Among all tests [here](https://github.com/Sdju/js-ini/blob/master/test/tests.ts) I was not able to find anything about passing improperly formatted text to `parse`.

But first pitfall for me was the lack of such scenario in README.

*Thanks for work there!*

**Comment by vintprox** [comment]
I love the idea of adding symbol into output object, it's so convenient.

**Comment by Sdju** [comment]
Thanks, for the issue. I will update test cases and README.
