### ISSUE TITLE
Parse hex number representation as decimal

### ISSUE THREAD

**Issue by dkoluris** [Sdju/js-ini#26]
Inside the .ini files if an assignment starts with `0x` (ex. 0xffff) it is the representation of an Integer number in Hex notation. But currently, this yields always a `0` after parsing. Is there a chance to fix this?

Thank you in advance.

**Comment by Sdju** [comment]
Hello, ok.
I will check if i can do smth with it

**Comment by Sdju** [comment]
Which way you would prefer: it should be parsed as a number(and yes, this is possible) or string "0xFF00".

I think the current library behaviour is a bug and after fixing this one it will be correctly parsed as a number (0xFF66AA => 16737962)

**Comment by dkoluris** [comment]
Thank you so much for the prompt reply. Yes, the hex representation should result in an integer after parsed like you mentioned.

**Comment by dkoluris** [comment]
Just tested the library, from me it's a successful run. You may close this ticket as "resolved", and again thank you for a wonderful library.
